apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-nfs-server
  template:
    metadata:
      labels:
        app: staging-nfs-server
    spec:
      containers:
      - name: staging-nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: staging-nfs-server-persistent-disk
      volumes:
        - name: staging-nfs-server-persistent-disk
          gcePersistentDisk:
            pdName: staging-nfs-disk
            fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: staging-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: staging-nfs-server
