apiVersion: v1
kind: Pod
metadata:
  name: staging-fabric-tools
spec:
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: staging-nfs-volume-claim
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:amd64-1.4.2
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: TZ
        value: "Asia/Bangkok"
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      volumeMounts:
        - mountPath: /fabric
          name: nfs-volume
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
