apiVersion: v1
kind: Service
metadata:
  name: staging-blockchain-ca
  labels:
    run: staging-blockchain-ca
spec:
  type: ClusterIP
  selector:
    name: staging-ca
  ports:
  - protocol: TCP
    port: 30054
    targetPort: 7054
    name: grpc
  - protocol: TCP
    port: 7054
    name: grpc1
