apiVersion: v1
kind: Service
metadata:
  name: staging-blockchain-orderer
  labels:
    run: staging-blockchain-orderer
spec:
  type: ClusterIP
  selector:
    name: staging-orderer
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
