apiVersion: v1
kind: Service
metadata:
  name: staging-fabric-application
  labels:
    run: staging-fabric-application
spec:
  type: ClusterIP 
  selector:
    name: staging-fabric-application
  ports:
    - port: 8888
      targetPort: 8888
