apiVersion: v1
kind: Service
metadata:
  name: production-blockchain-orderer
  labels:
    run: production-blockchain-orderer
spec:
  type: ClusterIP
  selector:
    name: production-orderer
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
