apiVersion: v1
kind: Service
metadata:
  name: production-blockchain-org1peer1
  labels:
    run: production-blockchain-org1peer1
spec:
  type: ClusterIP 
  selector:
    name: production-org1peer1
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
