apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: ClusterIP
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer2
  labels:
    run: blockchain-orderer2
spec:
  type: ClusterIP
  selector:
    name: orderer2
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
---
        
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer3
  labels:
    run: blockchain-orderer3
spec:
  type: ClusterIP
  selector:
    name: orderer3
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer4
  labels:
    run: blockchain-orderer4
spec:
  type: ClusterIP
  selector:
    name: orderer4
  ports:
  - protocol: TCP
    port: 31010
    name: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer5
  labels:
    run: blockchain-orderer5
spec:
  type: ClusterIP
  selector:
    name: orderer5
  ports:
  - protocol: TCP
    port: 31010
    name: grpc