apiVersion: v1
kind: Service
metadata:
  name: fabric-application
  labels:
    run: fabric-application
spec:
  type: ClusterIP 
  selector:
    name: fabric-application
  ports:
    - port: 8888
      targetPort: 8888
