apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: explorer
  template:
    metadata:
      labels:
        name: explorer
    spec:
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-volume-claim

      containers:
      - name: explorer
        image: hyperledger/explorer:0.3.8
        # resources:
        #   requests:
        #     cpu: 10m
        command: ["sh" , "-c" , "/fabric/config/explorer/app/run.sh"]
        env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /fabric
          name: nfs-volume
